package hlemu;

#if macro
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type;
using haxe.macro.Tools;
#end

/**
	Compile time support of the HL emulation for JS.

	- `init()` : call with `--macro hlemu.Macros.init(["dx", ...])` : remaps nothing by
	  itself (use `--remap hl:hlemu`), but adds `build()` to the given packages.
	- `@:struct` classes get the exact C layout of HashLink : fields are stored in an
	  ArrayBuffer (accessed through a DataView), whose native address is known, so the
	  struct can be passed to the addon like in HL.
	- `@:hlNative` methods call the addon (global `__dx12`), with the same naming rules
	  as the HL compiler.
**/
class Macros {

	#if macro

	public static function init( packs : Array<String> ) {
		for( p in packs )
			haxe.macro.Compiler.addGlobalMetadata(p, "@:build(hlemu.Macros.build())", true, true, false);
	}

	public static function build() : Array<Field> {
		var fields = Context.getBuildFields();
		var changed = rewriteStringMethods(fields);
		if( rewriteRemappedTypes(fields) ) changed = true;
		if( addDefaultValues(fields) ) changed = true;
		var t = Context.getLocalType();
		var res = switch( t ) {
		case TInst(c, _):
			var c = c.get();
			if( c.meta.has(":struct") )
				buildStruct(c, fields);
			else
				// abstracts are built through their implementation class
				buildNatives(c.meta.extract(":hlNative"), c.kind.match(KAbstractImpl(_)), fields);
		case TAbstract(a, _):
			buildNatives(a.get().meta.extract(":hlNative"), true, fields);
		default:
			null;
		}
		return res != null ? res : changed ? fields : null;
	}

	/**
		HL initializes basic typed fields (Int, Float, Bool...) to 0 / false, JS leaves them
		undefined : add the HL default values. Struct fields are in zeroed memory already.
	**/
	static function addDefaultValues( fields : Array<Field> ) : Bool {
		var changed = false;
		var cl = Context.getLocalClass();
		if( cl == null ) return false;
		var c = cl.get();
		if( c.meta.has(":struct") || c.isInterface || c.isExtern || !c.kind.match(KNormal) ) return false;
		// classes generated by hxsl macros (shaders, globals...) are left alone
		for( m in c.meta.extract(":build") )
			if( m.params.length > 0 && StringTools.startsWith(haxe.macro.ExprTools.toString(m.params[0]), "hxsl.") ) return false;
		var p = c;
		while( p != null ) {
			if( p.meta.has(":autoBuild") ) return false;
			p = p.superClass == null ? null : p.superClass.t.get();
		}
		for( f in fields ) {
			switch( f.kind ) {
			case FVar(t, null) if( t != null ):
				var e = defaultValue(t, f.pos);
				if( e != null ) {
					f.kind = FVar(t, e);
					changed = true;
				}
			case FProp(get, set, t, null) if( t != null && (get == "default" || get == "null") && (set == "default" || set == "null" || set == "never") ):
				var e = defaultValue(t, f.pos);
				if( e != null ) {
					f.kind = FProp(get, set, t, e);
					changed = true;
				}
			default:
			}
		}
		return changed;
	}

	static function defaultValue( ct : ComplexType, pos : Position ) : Expr {
		switch( ct ) {
		case TPath({ name : "Null", pack : [] }): return null;
		default:
		}
		var t = try Context.resolveType(ct, pos) catch( _ : Dynamic ) return null;
		function loop( t : Type ) : Expr {
			return switch( t ) {
			case TType(_): loop(Context.follow(t, true));
			case TLazy(f): loop(f());
			case TAbstract(a, _):
				var a = a.get();
				switch( a.pack.concat([a.name]).join(".") ) {
				case "Int", "Float", "Single", "hlemu.UI8", "hlemu.UI16", "hlemu.I64": macro cast 0;
				case "Bool": macro false;
				case "haxe.Int64", "haxe._Int64.Int64": macro haxe.Int64.make(0, 0);
				case "Null": null;
				default:
					if( a.meta.has(":coreType") ) null;
					// enum abstracts over Int, EnumFlags...
					else switch( Context.follow(a.type) ) {
					case TAbstract(b, _) if( b.get().name == "Int" && b.get().pack.length == 0 ): macro cast 0;
					default: null;
					}
				}
			default: null;
			}
		}
		return loop(t);
	}

	/**
		`--remap hl:hlemu` loses the type parameters of @:genericBuild types and constant
		type parameters (Haxe 5 preview) : these types are rewritten to hlemu directly.
	**/
	static var REMAP_DIRECT = ["BytesAccess", "Abstract"];

	static var remapChanged = false;

	static function rewriteRemappedTypes( fields : Array<Field> ) : Bool {
		remapChanged = false;
		for( f in fields ) mapField(f);
		return remapChanged;
	}

	static function mapType( t : ComplexType ) : ComplexType {
		if( t == null ) return null;
		return switch( t ) {
		case TPath(p):
			TPath(mapPath(p));
		case TFunction(args, ret):
			TFunction([for( a in args ) mapType(a)], mapType(ret));
		case TAnonymous(fl):
			TAnonymous([for( f in fl ) mapField(f)]);
		case TParent(t):
			TParent(mapType(t));
		case TOptional(t):
			TOptional(mapType(t));
		case TNamed(n, t):
			TNamed(n, mapType(t));
		default:
			t;
		}
	}
	static function mapPath( p : TypePath ) : TypePath {
		var pack = p.pack;
		if( pack.length == 1 && pack[0] == "hl" && REMAP_DIRECT.indexOf(p.name) >= 0 ) {
			pack = ["hlemu"];
			remapChanged = true;
		}
		return {
			pack : pack,
			name : p.name,
			sub : p.sub,
			params : p.params == null ? null : [for( tp in p.params ) switch( tp ) { case TPType(t): TPType(mapType(t)); default: tp; }],
		};
	}
	static function mapFun( f : Function ) {
		for( a in f.args ) a.type = mapType(a.type);
		f.ret = mapType(f.ret);
		if( f.expr != null ) f.expr = mapExpr(f.expr);
	}
	static function mapExpr( e : Expr ) : Expr {
		if( e == null ) return null;
		switch( e.expr ) {
		case EVars(vl):
			for( v in vl ) {
				v.type = mapType(v.type);
				v.expr = mapExpr(v.expr);
			}
			return e;
		case ECast(v, t):
			return { expr : ECast(mapExpr(v), mapType(t)), pos : e.pos };
		case ECheckType(v, t):
			return { expr : ECheckType(mapExpr(v), mapType(t)), pos : e.pos };
		case ENew(p, args):
			return { expr : ENew(mapPath(p), [for( a in args ) mapExpr(a)]), pos : e.pos };
		case EFunction(_, f):
			mapFun(f);
			return e;
		default:
			return haxe.macro.ExprTools.map(e, mapExpr);
		}
	}
	static function mapField( f : Field ) : Field {
		switch( f.kind ) {
		case FVar(t, e): f.kind = FVar(mapType(t), mapExpr(e));
		case FProp(g, s, t, e): f.kind = FProp(g, s, mapType(t), mapExpr(e));
		case FFun(fn): mapFun(fn);
		}
		return f;
	}


	/**
		HL strings have toUtf8() : x.toUtf8() calls are redirected to hlemu.StringExt
		(syntactically : the types are not known yet).
	**/
	static function rewriteStringMethods( fields : Array<Field> ) : Bool {
		var changed = false;
		function map( e : Expr ) : Expr {
			return switch( e.expr ) {
			case ECall({ expr : EField(obj, "toUtf8") }, []):
				changed = true;
				var o = map(obj);
				macro hlemu.StringExt.toUtf8($o);
			default:
				haxe.macro.ExprTools.map(e, map);
			}
		}
		for( f in fields )
			switch( f.kind ) {
			case FFun(fn) if( fn.expr != null ): fn.expr = map(fn.expr);
			default:
			}
		return changed;
	}

	// ---- types

	public static function classify( t : Type, packed : Bool ) : Kind {
		switch( t ) {
		case TType(_):
			return classify(Context.follow(t, true), packed);
		case TLazy(f):
			return classify(f(), packed);
		case TAbstract(a, params):
			var a = a.get();
			var path = a.pack.concat([a.name]).join(".");
			switch( path ) {
			case "Int": return KI32;
			case "Float": return KF64;
			case "Single": return KF32;
			case "Bool": return KBool;
			case "haxe.Int64", "haxe._Int64.Int64": return KInt64;
			case "hlemu.UI8": return KU8;
			case "hlemu.UI16": return KU16;
			case "hlemu.I64": return KNum64;
			case "hlemu.Bytes", "hlemu.Abstract": return KPtr;
			case "hlemu.CArray":
				return KPtrRef(switch( Context.follow(params[0]) ) { case TInst(c, _) if( c.get().meta.has(":struct") ): c.get(); default: null; });
			case "hlemu.NativeArray": return KArray;
			case "haxe.EnumFlags": return KFlags;
			case "Null": return KObject;
			default:
			}
			if( a.pack.join(".") == "hlemu" && StringTools.startsWith(a.name, "BytesAccess_") )
				return KPtr;
			if( a.meta.has(":coreType") )
				return KObject;
			return classify(a.type, packed);
		case TInst(c, _):
			var c = c.get();
			if( c.meta.has(":struct") )
				return packed ? KStruct(c) : KPtrRef(c);
			if( c.pack.join(".") == "hlemu" && c.name == "Abstract" )
				return KPtr;
			return KObject;
		default:
			return KObject;
		}
	}

	static function kindSize( k : Kind ) : { size : Int, align : Int } {
		return switch( k ) {
		case KBool, KU8: { size : 1, align : 1 };
		case KU16: { size : 2, align : 2 };
		case KI32, KF32, KFlags: { size : 4, align : 4 };
		case KF64, KInt64, KNum64, KPtr, KPtrRef(_): { size : 8, align : 8 };
		case KStruct(c): getLayout(c);
		case KArray, KObject, KRef: { size : 0, align : 1 };
		}
	}

	static function getLayout( c : ClassType ) : { size : Int, align : Int, end : Int, sync : Bool } {
		var m = c.meta.extract(":hlemuLayout");
		if( m.length == 0 ) {
			// force the build of the struct
			c.fields.get();
			m = c.meta.extract(":hlemuLayout");
			if( m.length == 0 ) Context.error("Struct layout of " + c.name + " is not known yet", c.pos);
		}
		var p = m[0].params;
		inline function int(e:Expr) return switch( e.expr ) { case EConst(CInt(v)): Std.parseInt(v); default: throw "assert"; }
		return { size : int(p[0]), align : int(p[1]), end : int(p[2]), sync : int(p[3]) != 0 };
	}

	// ---- structs

	static function buildStruct( c : ClassType, fields : Array<Field> ) : Array<Field> {
		var pos = Context.currentPos();
		var offset = 0, align = 1;
		var isRoot = true;
		// EnumFlags fields are normal JS fields (so that flags.set() works), copied to the
		// memory by __sync() before the struct is passed to a native function
		var syncs : Array<Expr> = [];
		var needSync = false;
		if( c.superClass != null && c.superClass.t.get().meta.has(":struct") ) {
			var l = getLayout(c.superClass.t.get());
			offset = l.end;
			align = l.align;
			needSync = l.sync;
			isRoot = false;
		}
		var out : Array<Field> = [];
		var ctPath = c.pack.concat([c.name]);
		var self = TPath({ pack : c.pack, name : c.module.split(".").pop(), sub : c.name == c.module.split(".").pop() ? null : c.name });

		for( f in fields ) {
			if( f.access.indexOf(AStatic) >= 0 ) {
				out.push(f);
				continue;
			}
			var ct, isReadOnly = false;
			switch( f.kind ) {
			case FVar(t, _):
				ct = t;
			case FProp("default", set, t, _) if( set == "null" || set == "never" || set == "default" ):
				ct = t;
				isReadOnly = set != "default";
			default:
				out.push(f);
				continue;
			}
			if( ct == null ) Context.error("Struct field requires a type", f.pos);
			var packed = f.meta != null && Lambda.exists(f.meta, m -> m.name == ":packed");
			var kind = classify(Context.resolveType(ct, f.pos), packed);
			switch( kind ) {
			case KObject, KArray, KRef:
				// not representable in memory : kept as a normal JS field
				out.push(f);
				continue;
			default:
			}
			var sz = kindSize(kind);
			offset = alignTo(offset, sz.align);
			if( sz.align > align ) align = sz.align;
			var off = offset;
			offset += sz.size;

			var name = f.name;
			var access = f.access.copy();
			var getName = "get_" + name, setName = "set_" + name;
			var o = macro this.__o + $v{off};
			var getter : Expr, setter : Expr = null;
			var extra : Array<Field> = [];
			switch( kind ) {
			case KFlags:
				syncs.push(macro this.__v.setInt32($o, cast this.$name, true));
				needSync = true;
				out.push(f);
				continue;
			case KBool:
				getter = macro return this.__v.getUint8($o) != 0;
				setter = macro { this.__v.setUint8($o, v ? 1 : 0); return v; };
			case KU8:
				getter = macro return cast this.__v.getUint8($o);
				setter = macro { this.__v.setUint8($o, cast v); return v; };
			case KU16:
				getter = macro return cast this.__v.getUint16($o, true);
				setter = macro { this.__v.setUint16($o, cast v, true); return v; };
			case KI32:
				getter = macro return cast this.__v.getInt32($o, true);
				setter = macro { this.__v.setInt32($o, cast v, true); return v; };
			case KF32:
				getter = macro return this.__v.getFloat32($o, true);
				setter = macro { this.__v.setFloat32($o, v, true); return v; };
			case KF64:
				getter = macro return this.__v.getFloat64($o, true);
				setter = macro { this.__v.setFloat64($o, v, true); return v; };
			case KInt64:
				getter = macro return haxe.Int64.make(this.__v.getInt32($o + 4, true), this.__v.getInt32($o, true));
				setter = macro { var x : haxe.Int64 = v; this.__v.setInt32($o, x.low, true); this.__v.setInt32($o + 4, x.high, true); return v; };
			case KNum64:
				getter = macro return cast hlemu.Struct.getNum64(this.__v, $o);
				setter = macro { hlemu.Struct.setNum64(this.__v, $o, cast v); return v; };
			case KPtr if( isBytesType(ct, f.pos) ):
				// In HL the GC follows the pointer : keep the haxe.io.Bytes it was converted from
				// alive (shader bytecode kept in a pipeline description, for instance)
				var ref = "__r_" + name;
				extra.push({ name : ref, kind : FVar(macro : haxe.io.Bytes), pos : f.pos, access : [APublic], meta : [{ name : ":noCompletion", pos : f.pos }] });
				getter = macro { var n = hlemu.Struct.getNum64(this.__v, $o); return n == 0 ? null : cast n; };
				setter = macro { this.$ref = hlemu.Bytes.convertedFrom(v); hlemu.Struct.setNum64(this.__v, $o, v == null ? 0 : cast v); return v; };
			case KPtr:
				getter = macro { var n = hlemu.Struct.getNum64(this.__v, $o); return n == 0 ? null : cast n; };
				setter = macro { hlemu.Struct.setNum64(this.__v, $o, v == null ? 0 : cast v); return v; };
			case KPtrRef(target):
				var ref = "__r_" + name;
				if( target == null || getLayout(target).sync ) {
					syncs.push(macro if( this.$ref != null ) (cast this.$ref).__sync());
					needSync = true;
				}
				extra.push({ name : ref, kind : FVar(ct), pos : f.pos, access : [APublic], meta : [{ name : ":noCompletion", pos : f.pos }] });
				getter = macro return this.$ref;
				setter = macro { this.$ref = v; hlemu.Struct.setNum64(this.__v, $o, hlemu.Struct.addr(v)); return v; };
			case KStruct(sc):
				var cache = "__p_" + name;
				extra.push({ name : cache, kind : FVar(ct), pos : f.pos, access : [], meta : [{ name : ":noCompletion", pos : f.pos }] });
				var scPath = sc.pack.concat([sc.module.split(".").pop()]);
				if( sc.name != sc.module.split(".").pop() ) scPath.push(sc.name);
				if( getLayout(sc).sync ) {
					syncs.push(macro { var s = this.$cache; if( s != null ) s.__sync(); });
					needSync = true;
				}
				getter = macro {
					var s = this.$cache;
					if( s == null ) this.$cache = s = $p{scPath}.__view(this.__v, $o, this.__a + $v{off});
					return s;
				};
				isReadOnly = true;
			case KObject, KArray, KRef:
				throw "assert";
			}
			out.push({ name : name, access : access, kind : FProp("get", isReadOnly ? "never" : "set", ct), pos : f.pos, meta : f.meta, doc : f.doc });
			out.push({ name : getName, access : [AInline], kind : FFun({ args : [], ret : ct, expr : getter }), pos : f.pos, meta : [{ name : ":noCompletion", pos : f.pos }] });
			if( !isReadOnly )
				out.push({ name : setName, access : [AInline], kind : FFun({ args : [{ name : "v", type : ct }], ret : ct, expr : setter }), pos : f.pos, meta : [{ name : ":noCompletion", pos : f.pos }] });
			for( e in extra ) out.push(e);
		}

		var end = offset;
		var size = alignTo(offset, align);
		c.meta.add(":hlemuLayout", [macro $v{size}, macro $v{align}, macro $v{end}, macro $v{needSync ? 1 : 0}], pos);

		if( isRoot ) {
			var noComp = [{ name : ":noCompletion", pos : pos }];
			out.push({ name : "__v", access : [APublic], kind : FVar(macro : js.lib.DataView), pos : pos, meta : noComp });
			out.push({ name : "__o", access : [APublic], kind : FVar(macro : Int), pos : pos, meta : noComp });
			out.push({ name : "__a", access : [APublic], kind : FVar(macro : Float), pos : pos, meta : noComp });
		}
		var keep = [{ name : ":keep", pos : pos }, { name : ":noCompletion", pos : pos }];
		if( isRoot )
			out.push({ name : "__sync", access : [APublic], pos : pos, meta : keep, kind : FFun({ args : [], ret : macro : Void, expr : macro $b{syncs} }) });
		else if( syncs.length > 0 )
			out.push({ name : "__sync", access : [APublic, AOverride], pos : pos, meta : keep, kind : FFun({ args : [], ret : macro : Void, expr : macro { super.__sync(); $b{syncs}; } }) });
		out.push({ name : "__NEEDSYNC", access : [APublic, AStatic], kind : FVar(macro : Bool, macro $v{needSync}), pos : pos, meta : keep });
		var cl = macro $p{ctPath};
		out.push({ name : "__SIZE", access : [APublic, AStatic], kind : FVar(macro : Int, macro $v{size}), pos : pos, meta : keep });
		out.push({ name : "__view", access : [APublic, AStatic], pos : pos, meta : keep, kind : FFun({
			args : [{ name : "v", type : macro : js.lib.DataView }, { name : "o", type : macro : Int }, { name : "a", type : macro : Float }],
			ret : self,
			expr : macro {
				var s : $self = js.Syntax.code("Object.create({0}.prototype)", $cl);
				s.__v = v;
				s.__o = o;
				s.__a = a;
				return s;
			}
		})});
		// memory allocation at construction
		for( f in out )
			if( f.name == "new" )
				switch( f.kind ) {
				case FFun(fn):
					fn.expr = macro { hlemu.Struct.alloc(this, $v{size}); ${fn.expr}; };
				default:
				}
		return out;
	}

	static function isBytesType( ct : ComplexType, pos : Position ) {
		return switch( Context.follow(Context.resolveType(ct, pos)) ) {
		case TAbstract(a, _): a.get().pack.join(".") == "hlemu" && a.get().name == "Bytes";
		default: false;
		}
	}

	static inline function alignTo( v : Int, a : Int ) {
		return (v + a - 1) & ~(a - 1);
	}

	// ---- natives

	static function nativeName( prefix : String, name : String ) {
		return prefix + ~/[A-Z]+/g.map(name, r -> "_" + r.matched(0)).toLowerCase();
	}

	static function isEmptyBody( e : Expr ) {
		if( e == null ) return true;
		return switch( e.expr ) {
		case EBlock([]): true;
		case EBlock([{ expr : EReturn({ expr : EConst(_) }) }]): true;
		default: false;
		}
	}

	static function buildNatives( classMeta : Array<MetadataEntry>, isAbstract : Bool, fields : Array<Field> ) : Array<Field> {
		var lib = null, prefix = "";
		for( m in classMeta ) {
			lib = getString(m.params[0]);
			if( m.params.length > 1 ) prefix = getString(m.params[1]);
		}
		var changed = false;
		for( f in fields ) {
			switch( f.kind ) {
			case FFun(fn):
				if( f.access.indexOf(AInline) >= 0 || f.access.indexOf(ADynamic) >= 0 || f.access.indexOf(AMacro) >= 0 ) continue;
				var native = null, flib = null;
				for( m in f.meta )
					if( m.name == ":hlNative" ) {
						flib = getString(m.params[0]);
						native = m.params.length > 1 ? getString(m.params[1]) : f.name;
					}
				if( native == null ) {
					if( lib == null || !isEmptyBody(fn.expr) || f.name == "new" ) continue;
					// class level : static methods only (and all methods of abstracts)
					if( !isAbstract && f.access.indexOf(AStatic) < 0 ) continue;
					flib = lib;
					native = nativeName(prefix, f.name);
				}
				var isStatic = f.access.indexOf(AStatic) >= 0;
				fn.expr = makeNativeCall(flib, native, fn, isAbstract && !isStatic, f.pos);
				changed = true;
			default:
			}
		}
		return changed ? fields : null;
	}

	static function getString( e : Expr ) {
		return switch( e.expr ) {
		case EConst(CString(s)): s;
		default: Context.error("String expected", e.pos);
		}
	}

	static function makeNativeCall( lib : String, name : String, fn : Function, withThis : Bool, pos : Position ) : Expr {
		if( lib != "dx12" ) {
			// optional libraries (?dx12debug) are not available in JS
			if( StringTools.startsWith(lib, "?") ) return macro {};
			Context.error("Native library " + lib + " is not available in JS", pos);
		}
		var args : Array<Expr> = [], pre : Array<Expr> = [], post : Array<Expr> = [];
		if( withThis ) args.push(macro this);
		for( a in fn.args ) {
			var e = macro $i{a.name};
			var kind = a.type == null ? KObject : classifyArg(a.type, pos);
			// HL accepts any BytesAccess<T> for a BytesAccess argument
			if( kind == KPtr && isBytesAccess(a.type) ) a.type = macro : hlemu.Bytes;
			switch( kind ) {
			case KInt64:
				args.push(macro hlemu.I64.ofInt64($e));
			case KPtrRef(_):
				args.push(macro hlemu.Struct.addrSync($e));
			case KArray:
				var tmp = "__arr_" + a.name;
				pre.push(macro var $tmp = hlemu.Struct.toVarray(cast $e));
				post.push(macro hlemu.Native.mem_free($i{tmp}));
				args.push(macro $i{tmp});
			case KRef:
				var tmp = "__ref_" + a.name;
				pre.push(macro var $tmp = hlemu.Native.mem_alloc(8));
				post.push(macro { $e.set(cast hlemu.Native.mem_get_i32($i{tmp})); hlemu.Native.mem_free($i{tmp}); });
				args.push(macro $i{tmp});
			case KObject:
				Context.error("Unsupported native argument type " + a.type.toString(), pos);
			default:
				args.push(e);
			}
		}
		var code = macro $v{"__dx12." + name + "(" + [for( i in 0...args.length ) "{" + i + "}"].join(",") + ")"};
		var call = { expr : ECall(macro js.Syntax.code, [code].concat(args)), pos : pos };
		var retKind = fn.ret == null ? KObject : (switch( fn.ret ) { case TPath({ name : "Void" }): null; default: classifyArg(fn.ret, pos); });
		var body : Array<Expr> = pre.copy();
		if( retKind == null ) {
			body.push(call);
			for( e in post ) body.push(e);
		} else {
			var conv = switch( retKind ) {
			case KInt64: macro hlemu.I64.toInt64(__r);
			case KArray: macro cast hlemu.Struct.fromVarray(__r);
			default: macro cast __r;
			};
			body.push(macro var __r : Dynamic = $call);
			for( e in post ) body.push(e);
			body.push(macro return $conv);
		}
		return macro $b{body};
	}

	static function isBytesAccess( ct : ComplexType ) {
		return switch( ct ) {
		case TPath({ name : "BytesAccess" }): true;
		default: false;
		}
	}

	static function classifyArg( ct : ComplexType, pos : Position ) : Kind {
		var t = Context.resolveType(ct, pos);
		switch( Context.follow(t) ) {
		case TInst(c, _) if( c.get().pack.join(".") == "hlemu" && c.get().name == "Ref" ):
			return KRef;
		default:
		}
		return classify(t, false);
	}

	// ---- hl.Bytes.getArray

	public static function getArray( e : Expr ) : Expr {
		// x.toData() : HL vectors, typed arrays in JS (h3d.shader.ShaderBufferData)
		switch( e.expr ) {
		case ECall({ expr : EField(x, "toData") }, []):
			switch( Context.followWithAbstracts(Context.typeof(x)) ) {
			case TInst(c, _) if( c.get().pack.join(".") == "js.lib" ):
				e = x;
			default:
			}
		default:
		}
		var t = Context.typeof(e);
		switch( Context.followWithAbstracts(t) ) {
		case TInst(c, [elt]) if( c.get().name == "Array" && c.get().pack.length == 0 ):
			// JS arrays have no native representation : copy (16 bits indexes)
			return macro hlemu.Struct.tmpUI16($e);
		case TInst(c, _) if( c.get().pack.join(".") == "js.lib" ):
			return macro (cast hlemu.Native.mem_address($e) : hlemu.Bytes);
		case TAnonymous(a) if( Lambda.exists(a.get().fields, f -> f.name == "array") ):
			// hxd.FloatBuffer on JS
			return macro (cast hlemu.Native.mem_address((cast $e).array) : hlemu.Bytes);
		default:
			Context.error("Unsupported getArray type " + t.toString(), e.pos);
			return null;
		}
	}

	// ---- hl.BytesAccess<T>

	public static function bytesAccess() : ComplexType {
		var pos = Context.currentPos();
		switch( Context.getLocalType() ) {
		case TInst(_, [t]):
			switch( t ) {
			case TInst(c, _) if( c.get().kind.match(KTypeParameter(_)) ):
				// not specialized (declaration itself)
				return macro : hlemu.Bytes;
			default:
			}
			var kind = classify(t, false);
			var ct = t.toComplexType();
			var name = "BytesAccess_" + switch( kind ) {
				case KPtr, KPtrRef(_), KNum64: "N64_" + StringTools.replace(t.toString(), ".", "_").split("<")[0];
				default: Std.string(kind);
			};
			try {
				Context.getType("hlemu." + name);
			} catch( _ : Dynamic ) {
				var size, get, set;
				var a = macro (cast this : Float) + (i << $v{0});
				switch( kind ) {
				case KI32: size = 2; get = macro cast hlemu.Native.mem_get_i32(p); set = macro hlemu.Native.mem_set_i32(p, cast v);
				case KU8: size = 0; get = macro cast hlemu.Native.mem_get_ui8(p); set = macro hlemu.Native.mem_set_ui8(p, cast v);
				case KU16: size = 1; get = macro cast hlemu.Native.mem_get_ui16(p); set = macro hlemu.Native.mem_set_ui16(p, cast v);
				case KF32: size = 2; get = macro hlemu.Native.mem_get_f32(p); set = macro hlemu.Native.mem_set_f32(p, v);
				case KF64: size = 3; get = macro hlemu.Native.mem_get_f64(p); set = macro hlemu.Native.mem_set_f64(p, v);
				case KInt64: size = 3; get = macro hlemu.I64.toInt64(hlemu.Native.mem_get_i64(p)); set = macro hlemu.Native.mem_set_i64(p, hlemu.I64.ofInt64(v));
				case KNum64, KPtr: size = 3; get = macro cast hlemu.Native.mem_get_i64(p); set = macro hlemu.Native.mem_set_i64(p, cast v);
				default: Context.error("Unsupported BytesAccess type " + t.toString(), pos);
				}
				var sizeBits = size;
				var def = macro class $name {
					public var sizeBits(get, never) : Int;
					inline function get_sizeBits() return $v{sizeBits};
					@:arrayAccess public inline function get( i : Int ) : $ct {
						var p = (cast this : Float) + (i << $v{sizeBits});
						return $get;
					}
					@:arrayAccess public inline function set( i : Int, v : $ct ) : $ct {
						var p = (cast this : Float) + (i << $v{sizeBits});
						$set;
						return v;
					}
					public inline function blit( pos : Int, src : hlemu.Bytes, srcPos : Int, len : Int ) : Void {
						(cast this : hlemu.Bytes).blit(pos << $v{sizeBits}, src, srcPos << $v{sizeBits}, len << $v{sizeBits});
					}
				};
				def.pack = ["hlemu"];
				def.kind = TDAbstract(macro : hlemu.Bytes, [AbFrom(macro : hlemu.Bytes), AbTo(macro : hlemu.Bytes)]);
				Context.defineType(def);
			}
			return TPath({ pack : ["hlemu"], name : name });
		default:
			throw "assert";
		}
	}

	#end
}

#if macro
enum Kind {
	KBool;
	KU8;
	KU16;
	KI32;
	KF32;
	KF64;
	/** haxe.Int64 **/
	KInt64;
	/** 64 bits integer stored as a JS number **/
	KNum64;
	/** pointer stored as a JS number, null when 0 **/
	KPtr;
	/** pointer to a struct or CArray (of the given struct) : the JS object is kept alive by the field **/
	KPtrRef( target : Null<ClassType> );
	/** haxe.EnumFlags : a normal JS field, synchronized before native calls **/
	KFlags;
	KStruct( c : ClassType );
	KArray;
	KRef;
	KObject;
}
#end
