package hlemu;

/**
	The dx12 Node-API addon (jsdx/native), loaded by the page as the global `__dx12`
	before the Haxe code starts.

	Only the memory primitives are declared here: the DirectX primitives are called by
	name from the code generated by `hlemu.NativeBind`.
**/
@:native("__dx12")
extern class Native {
	static function mem_alloc( size : Int ) : Float;
	static function mem_free( p : Float ) : Void;
	static function mem_copy( dst : Float, src : Float, size : Int ) : Void;
	static function mem_fill( dst : Float, value : Int, size : Int ) : Void;
	static function mem_get_ui8( p : Float ) : Int;
	static function mem_set_ui8( p : Float, v : Int ) : Void;
	static function mem_get_ui16( p : Float ) : Int;
	static function mem_set_ui16( p : Float, v : Int ) : Void;
	static function mem_get_i32( p : Float ) : Int;
	static function mem_set_i32( p : Float, v : Int ) : Void;
	static function mem_get_f32( p : Float ) : Float;
	static function mem_set_f32( p : Float, v : Float ) : Void;
	static function mem_get_f64( p : Float ) : Float;
	static function mem_set_f64( p : Float, v : Float ) : Void;
	static function mem_get_i64( p : Float ) : Float;
	static function mem_set_i64( p : Float, v : Float ) : Void;
	static function mem_ustrlen( p : Float ) : Int;
	/** native address of the data of an ArrayBuffer, TypedArray or DataView **/
	static function mem_address( buf : Dynamic ) : Float;
}
