package hlemu;

import hlemu.Native as N;

/**
	Runtime helpers for the code generated by hlemu.Macros.
**/
class Struct {

	/** allocates the memory of a new struct : a zeroed ArrayBuffer with a known address **/
	public static function alloc( s : Dynamic, size : Int ) : Void {
		var buf = new js.lib.ArrayBuffer(size > 0 ? size : 1);
		s.__v = new js.lib.DataView(buf);
		s.__o = 0;
		s.__a = N.mem_address(buf);
	}

	public static inline function getNum64( v : js.lib.DataView, o : Int ) : Float {
		return v.getUint32(o, true) + v.getInt32(o + 4, true) * 4294967296.;
	}

	public static inline function setNum64( v : js.lib.DataView, o : Int, x : Float ) : Void {
		var high = Math.floor(x / 4294967296.);
		v.setUint32(o, js.Syntax.code("(({0}) >>> 0)", x - high * 4294967296.), true);
		v.setInt32(o + 4, Std.int(high), true);
	}

	/** native address of a struct or CArray, 0 for null **/
	public static inline function addr( v : Dynamic ) : Float {
		return v == null ? 0 : v.__a;
	}

	/** native address of a struct or CArray passed to a native function : copies the pending fields to memory first **/
	public static inline function addrSync( v : Dynamic ) : Float {
		if( v == null ) return 0;
		v.__sync();
		return v.__a;
	}

	/** builds an HL varray of pointers / numbers in native memory, to free after the call **/
	public static function toVarray( a : Array<Dynamic> ) : Float {
		if( a == null ) return 0;
		var p = N.mem_alloc(24 + a.length * 8);
		N.mem_set_i32(p + 16, a.length);
		for( i in 0...a.length ) {
			var v : Dynamic = a[i];
			N.mem_set_i64(p + 24 + i * 8, v == null ? 0 : v);
		}
		return p;
	}

	/** reads an HL varray of pointers returned by the addon, and frees it **/
	public static function fromVarray( p : Float ) : Array<Dynamic> {
		if( p == null || p == 0 ) return null;
		var len = N.mem_get_i32(p + 16);
		var out = [];
		for( i in 0...len ) {
			var v = N.mem_get_i64(p + 24 + i * 8);
			out.push(v == 0 ? null : v);
		}
		N.mem_free(p);
		return out;
	}

	static var tmp : js.lib.Uint16Array;

	/** copies a JS array of 16 bits values into a temporary buffer, valid until the next call **/
	public static function tmpUI16( a : Array<Int> ) : hlemu.Bytes {
		tmp = new js.lib.Uint16Array(a);
		return cast N.mem_address(tmp);
	}
}
