name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: [latest, 4.3.7]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: krdlab/setup-haxe@v2
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - name: Print Haxe version
      run: |
        haxe --version
    - name: Build
      run: |
        haxelib git format https://github.com/HaxeFoundation/format
        haxelib git heaps https://github.com/HeapsIO/heaps
        haxelib git castle https://github.com/ncannasse/castle
        haxelib git hxbit https://github.com/ncannasse/hxbit
        haxelib git hscript https://github.com/HaxeFoundation/hscript
        haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
        haxelib git domkit https://github.com/HeapsIO/domkit
        haxelib git hx3compat https://github.com/HaxeFoundation/hx3compat
        haxelib git hashlink https://github.com/HaxeFoundation/hashlink master other/haxelib/
        haxe hide.hxml
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: js-${{ matrix.haxe-version }}
        path: |
          bin/*.js
          bin/*.js.map
    - name: Build HL
      if: matrix.haxe-version == 'latest'
      run: |
        haxelib git hldx https://github.com/HaxeFoundation/hashlink master libs/directx
        haxelib git hlphysics https://github.com/HeapsIO/hlphysics
        haxe hide_hl.hxml
    - name: Test - Build sample
      run: |
        haxelib dev hide .
        haxelib git hlsdl https://github.com/HaxeFoundation/hashlink master libs/sdl
        cd sample
        haxe hide-plugin.hxml
        haxe main.hxml
        cd ..

  deploy:
    if: github.repository_owner == 'HeapsIO' && github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && github.event_name != 'push'
    needs: build
    runs-on: ubuntu-latest
    env:
      electron-version: v44.7.0
    steps:
    - uses: actions/checkout@v6
    - name: Download js
      uses: actions/download-artifact@v8
      with:
        name: js-4.3.7
        path: bin
    - name: Install deploy packages
      run: sudo apt-get install p7zip-full
    - name: Windows
      run: |
        wget -O electron-win.zip https://github.com/electron/electron/releases/download/${{env.electron-version}}/electron-${{env.electron-version}}-win32-x64.zip
        mkdir -p zips
        cp -r bin zips/windows
        unzip -q electron-win.zip -d zips/windows/electron
        cd zips/windows
        7z a -mm=Deflate -mx=9 ../windows.zip *
        cd ../..
        rm -rf zips/windows
    - name: Linux
      run: |
        wget -O electron-linux.zip https://github.com/electron/electron/releases/download/${{env.electron-version}}/electron-${{env.electron-version}}-linux-x64.zip
        mkdir -p zips
        cp -r bin zips/linux
        unzip -q electron-linux.zip -d zips/linux/electron
        cd zips/linux
        7z a -mm=Deflate -mx=9 ../linux.zip *
        cd ../..
        rm -rf zips/linux
    - name: Mac
      run: |
        wget -O electron-mac.zip https://github.com/electron/electron/releases/download/${{env.electron-version}}/electron-${{env.electron-version}}-darwin-x64.zip
        mkdir -p zips/mac
        unzip -q electron-mac.zip -d zips/mac
        cp -r bin zips/mac/Electron.app/Contents/Resources/app
        cd zips/mac
        7z a -mm=Deflate -mx=9 ../mac.zip *
        cd ../..
        rm -rf zips/mac
    - name: Deploy
      run: |
        mkdir ~/.ssh
        echo "${{secrets.DEPLOY_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no zips/* gama11@community.heaps.io:builds/hide
